apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    # find all the pods with label comments
    matchLabels:
      app: comments
  template:
    # add label
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: zygu06/comments
---
# cluster ip service
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
# attach to comments-dep by label
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
