apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    # find all the pods with label event-bus
    matchLabels:
      app: event-bus
  template:
    # add label
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: zygu06/event-bus
---
# cluster ip service
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
# attach to even-bus-dep by label
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
