apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
  # find all the pods with label posts
    matchLabels:
      app: posts
  template:
  # add label
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: zygu06/posts
---
# cluster ip service
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000

