name: deploy-event-bus

on:
  push:
    branches:
      - main
    paths:
      - 'event-bus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd event-bus && docker build -t zygu06/event-bus .
      - run: docker push zygu06/event-bus
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save cmpt756-serverful
      - run: kubectl rollout restart deployment event-bus-depl